// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bcs.p3s.model;

import com.bcs.p3s.model.Epct;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Epct_Roo_Configurable {
    
    declare @type: Epct: @Configurable;
    
}
