// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bcs.p3s.model;

import com.bcs.p3s.model.ArchivedRate;
import com.bcs.p3s.model.ArchivedRateDataOnDemand;
import com.bcs.p3s.model.ArchivedRateIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ArchivedRateIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ArchivedRateIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ArchivedRateIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ArchivedRateIntegrationTest: @Transactional;
    
    @Autowired
    ArchivedRateDataOnDemand ArchivedRateIntegrationTest.dod;
    
    @Test
    public void ArchivedRateIntegrationTest.testCountArchivedRates() {
        Assert.assertNotNull("Data on demand for 'ArchivedRate' failed to initialize correctly", dod.getRandomArchivedRate());
        long count = ArchivedRate.countArchivedRates();
        Assert.assertTrue("Counter for 'ArchivedRate' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ArchivedRateIntegrationTest.testFindArchivedRate() {
        ArchivedRate obj = dod.getRandomArchivedRate();
        Assert.assertNotNull("Data on demand for 'ArchivedRate' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ArchivedRate' failed to provide an identifier", id);
        obj = ArchivedRate.findArchivedRate(id);
        Assert.assertNotNull("Find method for 'ArchivedRate' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ArchivedRate' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ArchivedRateIntegrationTest.testFindAllArchivedRates() {
        Assert.assertNotNull("Data on demand for 'ArchivedRate' failed to initialize correctly", dod.getRandomArchivedRate());
        long count = ArchivedRate.countArchivedRates();
        Assert.assertTrue("Too expensive to perform a find all test for 'ArchivedRate', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ArchivedRate> result = ArchivedRate.findAllArchivedRates();
        Assert.assertNotNull("Find all method for 'ArchivedRate' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ArchivedRate' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ArchivedRateIntegrationTest.testFindArchivedRateEntries() {
        Assert.assertNotNull("Data on demand for 'ArchivedRate' failed to initialize correctly", dod.getRandomArchivedRate());
        long count = ArchivedRate.countArchivedRates();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ArchivedRate> result = ArchivedRate.findArchivedRateEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ArchivedRate' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ArchivedRate' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ArchivedRateIntegrationTest.testFlush() {
        ArchivedRate obj = dod.getRandomArchivedRate();
        Assert.assertNotNull("Data on demand for 'ArchivedRate' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ArchivedRate' failed to provide an identifier", id);
        obj = ArchivedRate.findArchivedRate(id);
        Assert.assertNotNull("Find method for 'ArchivedRate' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyArchivedRate(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ArchivedRate' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ArchivedRateIntegrationTest.testMergeUpdate() {
        ArchivedRate obj = dod.getRandomArchivedRate();
        Assert.assertNotNull("Data on demand for 'ArchivedRate' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ArchivedRate' failed to provide an identifier", id);
        obj = ArchivedRate.findArchivedRate(id);
        boolean modified =  dod.modifyArchivedRate(obj);
        Integer currentVersion = obj.getVersion();
        ArchivedRate merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ArchivedRate' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ArchivedRateIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ArchivedRate' failed to initialize correctly", dod.getRandomArchivedRate());
        ArchivedRate obj = dod.getNewTransientArchivedRate(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ArchivedRate' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ArchivedRate' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'ArchivedRate' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ArchivedRateIntegrationTest.testRemove() {
        ArchivedRate obj = dod.getRandomArchivedRate();
        Assert.assertNotNull("Data on demand for 'ArchivedRate' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ArchivedRate' failed to provide an identifier", id);
        obj = ArchivedRate.findArchivedRate(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ArchivedRate' with identifier '" + id + "'", ArchivedRate.findArchivedRate(id));
    }
    
}
