// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bcs.p3s.model;

import com.bcs.p3s.model.Fee;
import com.bcs.p3s.model.FeeDataOnDemand;
import com.bcs.p3s.model.FeeIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FeeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FeeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FeeIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: FeeIntegrationTest: @Transactional;
    
    @Autowired
    FeeDataOnDemand FeeIntegrationTest.dod;
    
    @Test
    public void FeeIntegrationTest.testCountFees() {
        Assert.assertNotNull("Data on demand for 'Fee' failed to initialize correctly", dod.getRandomFee());
        long count = Fee.countFees();
        Assert.assertTrue("Counter for 'Fee' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FeeIntegrationTest.testFindFee() {
        Fee obj = dod.getRandomFee();
        Assert.assertNotNull("Data on demand for 'Fee' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Fee' failed to provide an identifier", id);
        obj = Fee.findFee(id);
        Assert.assertNotNull("Find method for 'Fee' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Fee' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void FeeIntegrationTest.testFindAllFees() {
        Assert.assertNotNull("Data on demand for 'Fee' failed to initialize correctly", dod.getRandomFee());
        long count = Fee.countFees();
        Assert.assertTrue("Too expensive to perform a find all test for 'Fee', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Fee> result = Fee.findAllFees();
        Assert.assertNotNull("Find all method for 'Fee' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Fee' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FeeIntegrationTest.testFindFeeEntries() {
        Assert.assertNotNull("Data on demand for 'Fee' failed to initialize correctly", dod.getRandomFee());
        long count = Fee.countFees();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Fee> result = Fee.findFeeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Fee' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Fee' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FeeIntegrationTest.testFlush() {
        Fee obj = dod.getRandomFee();
        Assert.assertNotNull("Data on demand for 'Fee' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Fee' failed to provide an identifier", id);
        obj = Fee.findFee(id);
        Assert.assertNotNull("Find method for 'Fee' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyFee(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Fee' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FeeIntegrationTest.testMergeUpdate() {
        Fee obj = dod.getRandomFee();
        Assert.assertNotNull("Data on demand for 'Fee' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Fee' failed to provide an identifier", id);
        obj = Fee.findFee(id);
        boolean modified =  dod.modifyFee(obj);
        Integer currentVersion = obj.getVersion();
        Fee merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Fee' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FeeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Fee' failed to initialize correctly", dod.getRandomFee());
        Fee obj = dod.getNewTransientFee(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Fee' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Fee' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Fee' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void FeeIntegrationTest.testRemove() {
        Fee obj = dod.getRandomFee();
        Assert.assertNotNull("Data on demand for 'Fee' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Fee' failed to provide an identifier", id);
        obj = Fee.findFee(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Fee' with identifier '" + id + "'", Fee.findFee(id));
    }
    
}
