// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bcs.p3s.model;

import com.bcs.p3s.model.GlobalVariableSole;
import com.bcs.p3s.model.GlobalVariableSoleDataOnDemand;
import com.bcs.p3s.model.GlobalVariableSoleIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect GlobalVariableSoleIntegrationTest_Roo_IntegrationTest {
    
    declare @type: GlobalVariableSoleIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: GlobalVariableSoleIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: GlobalVariableSoleIntegrationTest: @Transactional;
    
    @Autowired
    GlobalVariableSoleDataOnDemand GlobalVariableSoleIntegrationTest.dod;
    
    @Test
    public void GlobalVariableSoleIntegrationTest.testCountGlobalVariableSoles() {
        Assert.assertNotNull("Data on demand for 'GlobalVariableSole' failed to initialize correctly", dod.getRandomGlobalVariableSole());
        long count = GlobalVariableSole.countGlobalVariableSoles();
        Assert.assertTrue("Counter for 'GlobalVariableSole' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void GlobalVariableSoleIntegrationTest.testFindGlobalVariableSole() {
        GlobalVariableSole obj = dod.getRandomGlobalVariableSole();
        Assert.assertNotNull("Data on demand for 'GlobalVariableSole' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GlobalVariableSole' failed to provide an identifier", id);
        obj = GlobalVariableSole.findGlobalVariableSole(id);
        Assert.assertNotNull("Find method for 'GlobalVariableSole' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'GlobalVariableSole' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void GlobalVariableSoleIntegrationTest.testFindAllGlobalVariableSoles() {
        Assert.assertNotNull("Data on demand for 'GlobalVariableSole' failed to initialize correctly", dod.getRandomGlobalVariableSole());
        long count = GlobalVariableSole.countGlobalVariableSoles();
        Assert.assertTrue("Too expensive to perform a find all test for 'GlobalVariableSole', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<GlobalVariableSole> result = GlobalVariableSole.findAllGlobalVariableSoles();
        Assert.assertNotNull("Find all method for 'GlobalVariableSole' illegally returned null", result);
        Assert.assertTrue("Find all method for 'GlobalVariableSole' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void GlobalVariableSoleIntegrationTest.testFindGlobalVariableSoleEntries() {
        Assert.assertNotNull("Data on demand for 'GlobalVariableSole' failed to initialize correctly", dod.getRandomGlobalVariableSole());
        long count = GlobalVariableSole.countGlobalVariableSoles();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<GlobalVariableSole> result = GlobalVariableSole.findGlobalVariableSoleEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'GlobalVariableSole' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'GlobalVariableSole' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void GlobalVariableSoleIntegrationTest.testFlush() {
        GlobalVariableSole obj = dod.getRandomGlobalVariableSole();
        Assert.assertNotNull("Data on demand for 'GlobalVariableSole' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GlobalVariableSole' failed to provide an identifier", id);
        obj = GlobalVariableSole.findGlobalVariableSole(id);
        Assert.assertNotNull("Find method for 'GlobalVariableSole' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyGlobalVariableSole(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'GlobalVariableSole' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void GlobalVariableSoleIntegrationTest.testMergeUpdate() {
        GlobalVariableSole obj = dod.getRandomGlobalVariableSole();
        Assert.assertNotNull("Data on demand for 'GlobalVariableSole' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GlobalVariableSole' failed to provide an identifier", id);
        obj = GlobalVariableSole.findGlobalVariableSole(id);
        boolean modified =  dod.modifyGlobalVariableSole(obj);
        Integer currentVersion = obj.getVersion();
        GlobalVariableSole merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'GlobalVariableSole' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void GlobalVariableSoleIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'GlobalVariableSole' failed to initialize correctly", dod.getRandomGlobalVariableSole());
        GlobalVariableSole obj = dod.getNewTransientGlobalVariableSole(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'GlobalVariableSole' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'GlobalVariableSole' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'GlobalVariableSole' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void GlobalVariableSoleIntegrationTest.testRemove() {
        GlobalVariableSole obj = dod.getRandomGlobalVariableSole();
        Assert.assertNotNull("Data on demand for 'GlobalVariableSole' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GlobalVariableSole' failed to provide an identifier", id);
        obj = GlobalVariableSole.findGlobalVariableSole(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'GlobalVariableSole' with identifier '" + id + "'", GlobalVariableSole.findGlobalVariableSole(id));
    }
    
}
