// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bcs.p3s.model;

import com.bcs.p3s.model.P3SFeeSole;
import com.bcs.p3s.model.P3SFeeSoleDataOnDemand;
import com.bcs.p3s.model.P3SFeeSoleIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect P3SFeeSoleIntegrationTest_Roo_IntegrationTest {
    
    declare @type: P3SFeeSoleIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: P3SFeeSoleIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: P3SFeeSoleIntegrationTest: @Transactional;
    
    @Autowired
    P3SFeeSoleDataOnDemand P3SFeeSoleIntegrationTest.dod;
    
    @Test
    public void P3SFeeSoleIntegrationTest.testCountP3SFeeSoles() {
        Assert.assertNotNull("Data on demand for 'P3SFeeSole' failed to initialize correctly", dod.getRandomP3SFeeSole());
        long count = P3SFeeSole.countP3SFeeSoles();
        Assert.assertTrue("Counter for 'P3SFeeSole' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void P3SFeeSoleIntegrationTest.testFindP3SFeeSole() {
        P3SFeeSole obj = dod.getRandomP3SFeeSole();
        Assert.assertNotNull("Data on demand for 'P3SFeeSole' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'P3SFeeSole' failed to provide an identifier", id);
        obj = P3SFeeSole.findP3SFeeSole(id);
        Assert.assertNotNull("Find method for 'P3SFeeSole' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'P3SFeeSole' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void P3SFeeSoleIntegrationTest.testFindAllP3SFeeSoles() {
        Assert.assertNotNull("Data on demand for 'P3SFeeSole' failed to initialize correctly", dod.getRandomP3SFeeSole());
        long count = P3SFeeSole.countP3SFeeSoles();
        Assert.assertTrue("Too expensive to perform a find all test for 'P3SFeeSole', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<P3SFeeSole> result = P3SFeeSole.findAllP3SFeeSoles();
        Assert.assertNotNull("Find all method for 'P3SFeeSole' illegally returned null", result);
        Assert.assertTrue("Find all method for 'P3SFeeSole' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void P3SFeeSoleIntegrationTest.testFindP3SFeeSoleEntries() {
        Assert.assertNotNull("Data on demand for 'P3SFeeSole' failed to initialize correctly", dod.getRandomP3SFeeSole());
        long count = P3SFeeSole.countP3SFeeSoles();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<P3SFeeSole> result = P3SFeeSole.findP3SFeeSoleEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'P3SFeeSole' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'P3SFeeSole' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void P3SFeeSoleIntegrationTest.testFlush() {
        P3SFeeSole obj = dod.getRandomP3SFeeSole();
        Assert.assertNotNull("Data on demand for 'P3SFeeSole' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'P3SFeeSole' failed to provide an identifier", id);
        obj = P3SFeeSole.findP3SFeeSole(id);
        Assert.assertNotNull("Find method for 'P3SFeeSole' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyP3SFeeSole(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'P3SFeeSole' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void P3SFeeSoleIntegrationTest.testMergeUpdate() {
        P3SFeeSole obj = dod.getRandomP3SFeeSole();
        Assert.assertNotNull("Data on demand for 'P3SFeeSole' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'P3SFeeSole' failed to provide an identifier", id);
        obj = P3SFeeSole.findP3SFeeSole(id);
        boolean modified =  dod.modifyP3SFeeSole(obj);
        Integer currentVersion = obj.getVersion();
        P3SFeeSole merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'P3SFeeSole' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void P3SFeeSoleIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'P3SFeeSole' failed to initialize correctly", dod.getRandomP3SFeeSole());
        P3SFeeSole obj = dod.getNewTransientP3SFeeSole(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'P3SFeeSole' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'P3SFeeSole' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'P3SFeeSole' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void P3SFeeSoleIntegrationTest.testRemove() {
        P3SFeeSole obj = dod.getRandomP3SFeeSole();
        Assert.assertNotNull("Data on demand for 'P3SFeeSole' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'P3SFeeSole' failed to provide an identifier", id);
        obj = P3SFeeSole.findP3SFeeSole(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'P3SFeeSole' with identifier '" + id + "'", P3SFeeSole.findP3SFeeSole(id));
    }
    
}
