// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bcs.p3s.model;

import com.bcs.p3s.model.P3SUser;
import com.bcs.p3s.model.P3SUserDataOnDemand;
import com.bcs.p3s.model.P3SUserIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect P3SUserIntegrationTest_Roo_IntegrationTest {
    
    declare @type: P3SUserIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: P3SUserIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: P3SUserIntegrationTest: @Transactional;
    
    @Autowired
    P3SUserDataOnDemand P3SUserIntegrationTest.dod;
    
    @Test
    public void P3SUserIntegrationTest.testCountP3SUsers() {
        Assert.assertNotNull("Data on demand for 'P3SUser' failed to initialize correctly", dod.getRandomP3SUser());
        long count = P3SUser.countP3SUsers();
        Assert.assertTrue("Counter for 'P3SUser' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void P3SUserIntegrationTest.testFindP3SUser() {
        P3SUser obj = dod.getRandomP3SUser();
        Assert.assertNotNull("Data on demand for 'P3SUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'P3SUser' failed to provide an identifier", id);
        obj = P3SUser.findP3SUser(id);
        Assert.assertNotNull("Find method for 'P3SUser' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'P3SUser' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void P3SUserIntegrationTest.testFindAllP3SUsers() {
        Assert.assertNotNull("Data on demand for 'P3SUser' failed to initialize correctly", dod.getRandomP3SUser());
        long count = P3SUser.countP3SUsers();
        Assert.assertTrue("Too expensive to perform a find all test for 'P3SUser', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<P3SUser> result = P3SUser.findAllP3SUsers();
        Assert.assertNotNull("Find all method for 'P3SUser' illegally returned null", result);
        Assert.assertTrue("Find all method for 'P3SUser' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void P3SUserIntegrationTest.testFindP3SUserEntries() {
        Assert.assertNotNull("Data on demand for 'P3SUser' failed to initialize correctly", dod.getRandomP3SUser());
        long count = P3SUser.countP3SUsers();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<P3SUser> result = P3SUser.findP3SUserEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'P3SUser' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'P3SUser' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void P3SUserIntegrationTest.testFlush() {
        P3SUser obj = dod.getRandomP3SUser();
        Assert.assertNotNull("Data on demand for 'P3SUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'P3SUser' failed to provide an identifier", id);
        obj = P3SUser.findP3SUser(id);
        Assert.assertNotNull("Find method for 'P3SUser' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyP3SUser(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'P3SUser' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void P3SUserIntegrationTest.testMergeUpdate() {
        P3SUser obj = dod.getRandomP3SUser();
        Assert.assertNotNull("Data on demand for 'P3SUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'P3SUser' failed to provide an identifier", id);
        obj = P3SUser.findP3SUser(id);
        boolean modified =  dod.modifyP3SUser(obj);
        Integer currentVersion = obj.getVersion();
        P3SUser merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'P3SUser' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void P3SUserIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'P3SUser' failed to initialize correctly", dod.getRandomP3SUser());
        P3SUser obj = dod.getNewTransientP3SUser(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'P3SUser' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'P3SUser' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'P3SUser' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void P3SUserIntegrationTest.testRemove() {
        P3SUser obj = dod.getRandomP3SUser();
        Assert.assertNotNull("Data on demand for 'P3SUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'P3SUser' failed to provide an identifier", id);
        obj = P3SUser.findP3SUser(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'P3SUser' with identifier '" + id + "'", P3SUser.findP3SUser(id));
    }
    
}
