// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bcs.p3s.model;

import com.bcs.p3s.model.Form1200;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Form1200_Roo_Configurable {
    
    declare @type: Form1200: @Configurable;
    
}
