package com.bcs.p3s.controller.web;
import com.bcs.p3s.model.Business;
import org.springframework.roo.addon.web.mvc.controller.scaffold.RooWebScaffold;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;


/** AC 180607 
 * This class appears to be:
 * - generated by ROO
 * - unused
 * 
 * Hence giving notice here that it will be deleted in time
 */



@RequestMapping("/businesses")
@Controller
@RooWebScaffold(path = "businesses", formBackingObject = Business.class)
public class BusinessController {
}
