// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bcs.p3s.model;

import com.bcs.p3s.model.Business;
import com.bcs.p3s.model.BusinessDataOnDemand;
import com.bcs.p3s.model.BusinessIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect BusinessIntegrationTest_Roo_IntegrationTest {
    
    declare @type: BusinessIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: BusinessIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: BusinessIntegrationTest: @Transactional;
    
    @Autowired
    BusinessDataOnDemand BusinessIntegrationTest.dod;
    
    @Test
    public void BusinessIntegrationTest.testCountBusinesses() {
        Assert.assertNotNull("Data on demand for 'Business' failed to initialize correctly", dod.getRandomBusiness());
        long count = Business.countBusinesses();
        Assert.assertTrue("Counter for 'Business' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void BusinessIntegrationTest.testFindBusiness() {
        Business obj = dod.getRandomBusiness();
        Assert.assertNotNull("Data on demand for 'Business' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Business' failed to provide an identifier", id);
        obj = Business.findBusiness(id);
        Assert.assertNotNull("Find method for 'Business' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Business' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void BusinessIntegrationTest.testFindAllBusinesses() {
        Assert.assertNotNull("Data on demand for 'Business' failed to initialize correctly", dod.getRandomBusiness());
        long count = Business.countBusinesses();
        Assert.assertTrue("Too expensive to perform a find all test for 'Business', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Business> result = Business.findAllBusinesses();
        Assert.assertNotNull("Find all method for 'Business' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Business' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void BusinessIntegrationTest.testFindBusinessEntries() {
        Assert.assertNotNull("Data on demand for 'Business' failed to initialize correctly", dod.getRandomBusiness());
        long count = Business.countBusinesses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Business> result = Business.findBusinessEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Business' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Business' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void BusinessIntegrationTest.testFlush() {
        Business obj = dod.getRandomBusiness();
        Assert.assertNotNull("Data on demand for 'Business' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Business' failed to provide an identifier", id);
        obj = Business.findBusiness(id);
        Assert.assertNotNull("Find method for 'Business' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyBusiness(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Business' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BusinessIntegrationTest.testMergeUpdate() {
        Business obj = dod.getRandomBusiness();
        Assert.assertNotNull("Data on demand for 'Business' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Business' failed to provide an identifier", id);
        obj = Business.findBusiness(id);
        boolean modified =  dod.modifyBusiness(obj);
        Integer currentVersion = obj.getVersion();
        Business merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Business' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BusinessIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Business' failed to initialize correctly", dod.getRandomBusiness());
        Business obj = dod.getNewTransientBusiness(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Business' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Business' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Business' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void BusinessIntegrationTest.testRemove() {
        Business obj = dod.getRandomBusiness();
        Assert.assertNotNull("Data on demand for 'Business' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Business' failed to provide an identifier", id);
        obj = Business.findBusiness(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Business' with identifier '" + id + "'", Business.findBusiness(id));
    }
    
}
