// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bcs.p3s.model;

import com.bcs.p3s.model.EpoFeeDataOnDemand;
import com.bcs.p3s.model.EpoRenewalFee;
import java.math.BigDecimal;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect EpoFeeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: EpoFeeDataOnDemand: @Component;
    
    private Random EpoFeeDataOnDemand.rnd = new SecureRandom();
    
    private List<EpoRenewalFee> EpoFeeDataOnDemand.data;
    
    public EpoRenewalFee EpoFeeDataOnDemand.getNewTransientEpoRenewalFee(int index) {
        EpoRenewalFee obj = new EpoRenewalFee();
        setExtensionFee_EUR(obj, index);
        setRenewalFee_EUR(obj, index);
        setRenewalYear(obj, index);
        return obj;
    }
    
    public void EpoFeeDataOnDemand.setExtensionFee_EUR(EpoRenewalFee obj, int index) {
        BigDecimal extensionFee_EUR = BigDecimal.valueOf(index);
        obj.setExtensionFee_EUR(extensionFee_EUR);
    }
    
    public void EpoFeeDataOnDemand.setRenewalFee_EUR(EpoRenewalFee obj, int index) {
        BigDecimal renewalFee_EUR = BigDecimal.valueOf(index);
        obj.setRenewalFee_EUR(renewalFee_EUR);
    }
    
    public void EpoFeeDataOnDemand.setRenewalYear(EpoRenewalFee obj, int index) {
        Integer renewalYear = new Integer(index);
        obj.setRenewalYear(renewalYear);
    }
    
    public EpoRenewalFee EpoFeeDataOnDemand.getSpecificEpoRenewalFee(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        EpoRenewalFee obj = data.get(index);
        Long id = obj.getId();
        return EpoRenewalFee.findEpoRenewalFee(id);
    }
    
    public EpoRenewalFee EpoFeeDataOnDemand.getRandomEpoRenewalFee() {
        init();
        EpoRenewalFee obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return EpoRenewalFee.findEpoRenewalFee(id);
    }
    
    public boolean EpoFeeDataOnDemand.modifyEpoRenewalFee(EpoRenewalFee obj) {
        return false;
    }
    
    public void EpoFeeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = EpoRenewalFee.findEpoRenewalFeeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'EpoRenewalFee' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<EpoRenewalFee>();
        for (int i = 0; i < 10; i++) {
            EpoRenewalFee obj = getNewTransientEpoRenewalFee(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
